// Mocks generated by Mockito 5.4.4 from annotations
// in tulink_flutter/test/features/profile/presentation/profile_logout_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tulink_flutter/core/errors/failure.dart' as _i4;
import 'package:tulink_flutter/features/analytics/presentation/providers/analytics_provider.dart'
    as _i6;
import 'package:tulink_flutter/features/auth/domain/entities/user_entity.dart'
    as _i5;
import 'package:tulink_flutter/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:tulink_flutter/features/convoy/domain/entities/convoy_snapshot.dart'
    as _i10;
import 'package:tulink_flutter/features/convoy/presentation/providers/convoy_provider.dart'
    as _i9;
import 'package:tulink_flutter/features/journeys/domain/entities/journey.dart'
    as _i7;
import 'package:tulink_flutter/features/maps/data/models/route_result_model.dart'
    as _i13;
import 'package:tulink_flutter/features/maps/domain/entities/maneuver.dart'
    as _i12;
import 'package:tulink_flutter/features/maps/presentation/providers/navigation_provider.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signIn({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signUp({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
            returnValueForMissingStub:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, _i5.UserEntity? user})
                >.value((failure: null, user: null)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, _i5.UserEntity? user})
                >.value((failure: null, user: null)),
          )
          as _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})>);

  @override
  _i3.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<({_i4.Failure? failure, String? token})> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, String? token})>.value((
                  failure: null,
                  token: null,
                )),
            returnValueForMissingStub:
                _i3.Future<({_i4.Failure? failure, String? token})>.value((
                  failure: null,
                  token: null,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, String? token})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
            returnValueForMissingStub:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> verifyEmail({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
            returnValueForMissingStub:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})> updateProfile({
    String? name,
    String? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #profilePicture: profilePicture,
            }),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, _i5.UserEntity? user})
                >.value((failure: null, user: null)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, _i5.UserEntity? user})
                >.value((failure: null, user: null)),
          )
          as _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
            returnValueForMissingStub:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
            returnValueForMissingStub:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool isEmailVerified})>
  checkEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailVerification, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, bool isEmailVerified})
                >.value((failure: null, isEmailVerified: false)),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i4.Failure? failure, bool isEmailVerified})
                >.value((failure: null, isEmailVerified: false)),
          )
          as _i3.Future<({_i4.Failure? failure, bool isEmailVerified})>);
}

/// A class which mocks [AnalyticsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsProvider extends _i1.Mock implements _i6.AnalyticsProvider {
  @override
  List<_i7.Journey> get recentJourneys =>
      (super.noSuchMethod(
            Invocation.getter(#recentJourneys),
            returnValue: <_i7.Journey>[],
            returnValueForMissingStub: <_i7.Journey>[],
          )
          as List<_i7.Journey>);

  @override
  List<_i7.Journey> get journeyHistory =>
      (super.noSuchMethod(
            Invocation.getter(#journeyHistory),
            returnValue: <_i7.Journey>[],
            returnValueForMissingStub: <_i7.Journey>[],
          )
          as List<_i7.Journey>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSummaryLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isSummaryLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> loadJourneySummary(String? journeyId) =>
      (super.noSuchMethod(
            Invocation.method(#loadJourneySummary, [journeyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadRecentJourneys({int? limit = 4}) =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentJourneys, [], {#limit: limit}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadJourneyHistory({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#loadJourneyHistory, [], {#limit: limit}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i7.Journey?> getJourneyAnalytics(String? journeyId) =>
      (super.noSuchMethod(
            Invocation.method(#getJourneyAnalytics, [journeyId]),
            returnValue: _i3.Future<_i7.Journey?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.Journey?>.value(),
          )
          as _i3.Future<_i7.Journey?>);

  @override
  _i3.Future<void> refreshRecentJourneys() =>
      (super.noSuchMethod(
            Invocation.method(#refreshRecentJourneys, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshJourneyHistory() =>
      (super.noSuchMethod(
            Invocation.method(#refreshJourneyHistory, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConvoyProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvoyProvider extends _i1.Mock implements _i9.ConvoyProvider {
  @override
  int get arrivedCount =>
      (super.noSuchMethod(
            Invocation.getter(#arrivedCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get totalMemberCount =>
      (super.noSuchMethod(
            Invocation.getter(#totalMemberCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get participantAcceptedTick =>
      (super.noSuchMethod(
            Invocation.getter(#participantAcceptedTick),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get journeyInviteTick =>
      (super.noSuchMethod(
            Invocation.getter(#journeyInviteTick),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isPublishing =>
      (super.noSuchMethod(
            Invocation.getter(#isPublishing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSubscribed =>
      (super.noSuchMethod(
            Invocation.getter(#isSubscribed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.ConvoyConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i10.ConvoyConnectionState.disconnected,
            returnValueForMissingStub: _i10.ConvoyConnectionState.disconnected,
          )
          as _i10.ConvoyConnectionState);

  @override
  bool get isCoordinating =>
      (super.noSuchMethod(
            Invocation.getter(#isCoordinating),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get connectionAttemptId =>
      (super.noSuchMethod(
            Invocation.getter(#connectionAttemptId),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> reconnect(String? journeyId) =>
      (super.noSuchMethod(
            Invocation.method(#reconnect, [journeyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> retryLocationPublishing() =>
      (super.noSuchMethod(
            Invocation.method(#retryLocationPublishing, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> onAppResumed() =>
      (super.noSuchMethod(
            Invocation.method(#onAppResumed, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startCoordination(String? journeyId) =>
      (super.noSuchMethod(
            Invocation.method(#startCoordination, [journeyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startUserChannel() =>
      (super.noSuchMethod(
            Invocation.method(#startUserChannel, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopUserChannel() =>
      (super.noSuchMethod(
            Invocation.method(#stopUserChannel, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> joinJourneyRoom(String? journeyId) =>
      (super.noSuchMethod(
            Invocation.method(#joinJourneyRoom, [journeyId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> stopCoordination({bool? invalidateRoomOwner = true}) =>
      (super.noSuchMethod(
            Invocation.method(#stopCoordination, [], {
              #invalidateRoomOwner: invalidateRoomOwner,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void consumeArrivalEvent() => super.noSuchMethod(
    Invocation.method(#consumeArrivalEvent, []),
    returnValueForMissingStub: null,
  );

  @override
  void consumeJourneyEndedEvent() => super.noSuchMethod(
    Invocation.method(#consumeJourneyEndedEvent, []),
    returnValueForMissingStub: null,
  );

  @override
  void consumeJourneyStartedEvent() => super.noSuchMethod(
    Invocation.method(#consumeJourneyStartedEvent, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> refreshSnapshot(String? journeyId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSnapshot, [journeyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i10.ConvoySnapshot? getDisplaySnapshot(String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplaySnapshot, [currentUserId]),
            returnValueForMissingStub: null,
          )
          as _i10.ConvoySnapshot?);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSnapshotForTesting(_i10.ConvoySnapshot? snapshot) =>
      super.noSuchMethod(
        Invocation.method(#setSnapshotForTesting, [snapshot]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i11.NavigationProvider {
  @override
  bool get offlineReroutePending =>
      (super.noSuchMethod(
            Invocation.getter(#offlineReroutePending),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNavigating =>
      (super.noSuchMethod(
            Invocation.getter(#isNavigating),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isVoiceEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isVoiceEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i12.Maneuver> get maneuvers =>
      (super.noSuchMethod(
            Invocation.getter(#maneuvers),
            returnValue: <_i12.Maneuver>[],
            returnValueForMissingStub: <_i12.Maneuver>[],
          )
          as List<_i12.Maneuver>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> initializePreferences() =>
      (super.noSuchMethod(
            Invocation.method(#initializePreferences, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startNavigation({
    required _i13.RouteResultModel? route,
    required _i3.Future<void> Function()? onRerouteNeeded,
    String? journeyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startNavigation, [], {
              #route: route,
              #onRerouteNeeded: onRerouteNeeded,
              #journeyId: journeyId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void loadRoute(_i13.RouteResultModel? route) => super.noSuchMethod(
    Invocation.method(#loadRoute, [route]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> stopNavigation() =>
      (super.noSuchMethod(
            Invocation.method(#stopNavigation, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setVoiceEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setVoiceEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
