// Mocks generated by Mockito 5.4.4 from annotations
// in tulink_flutter/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:firebase_messaging/firebase_messaging.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tulink_flutter/core/network/dio_client.dart' as _i8;
import 'package:tulink_flutter/core/services/push_notification_service.dart'
    as _i10;
import 'package:tulink_flutter/features/auth/data/datasources/auth_local_data_source.dart'
    as _i7;
import 'package:tulink_flutter/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i4;
import 'package:tulink_flutter/features/auth/data/models/user_model.dart'
    as _i2;
import 'package:tulink_flutter/features/auth/data/services/social_auth_service.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<({String? refreshToken, String token, _i2.UserModel user})>
      signIn({
    required String? email,
    required String? password,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #signIn,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
            returnValue: _i5.Future<
                ({
                  String? refreshToken,
                  String token,
                  _i2.UserModel user
                })>.value((
              refreshToken: null,
              token: _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #signIn,
                  [],
                  {
                    #email: email,
                    #password: password,
                  },
                ),
              ),
              user: _FakeUserModel_0(
                this,
                Invocation.method(
                  #signIn,
                  [],
                  {
                    #email: email,
                    #password: password,
                  },
                ),
              )
            )),
          ) as _i5.Future<
              ({String? refreshToken, String token, _i2.UserModel user})>);

  @override
  _i5.Future<({String? refreshToken, String token, _i2.UserModel user})>
      signUp({
    required String? email,
    required String? password,
    required String? name,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #signUp,
              [],
              {
                #email: email,
                #password: password,
                #name: name,
              },
            ),
            returnValue: _i5.Future<
                ({
                  String? refreshToken,
                  String token,
                  _i2.UserModel user
                })>.value((
              refreshToken: null,
              token: _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #signUp,
                  [],
                  {
                    #email: email,
                    #password: password,
                    #name: name,
                  },
                ),
              ),
              user: _FakeUserModel_0(
                this,
                Invocation.method(
                  #signUp,
                  [],
                  {
                    #email: email,
                    #password: password,
                    #name: name,
                  },
                ),
              )
            )),
          ) as _i5.Future<
              ({String? refreshToken, String token, _i2.UserModel user})>);

  @override
  _i5.Future<({String? refreshToken, String token, _i2.UserModel user})>
      signInWithSocial({
    required String? provider,
    required String? idToken,
    String? nonce,
    String? displayName,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #signInWithSocial,
              [],
              {
                #provider: provider,
                #idToken: idToken,
                #nonce: nonce,
                #displayName: displayName,
              },
            ),
            returnValue: _i5.Future<
                ({
                  String? refreshToken,
                  String token,
                  _i2.UserModel user
                })>.value((
              refreshToken: null,
              token: _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #signInWithSocial,
                  [],
                  {
                    #provider: provider,
                    #idToken: idToken,
                    #nonce: nonce,
                    #displayName: displayName,
                  },
                ),
              ),
              user: _FakeUserModel_0(
                this,
                Invocation.method(
                  #signInWithSocial,
                  [],
                  {
                    #provider: provider,
                    #idToken: idToken,
                    #nonce: nonce,
                    #displayName: displayName,
                  },
                ),
              )
            )),
          ) as _i5.Future<
              ({String? refreshToken, String token, _i2.UserModel user})>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserModel> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<String> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> resetPassword({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {#email: email},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> verifyEmail({required String? token}) => (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [],
          {#token: token},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> checkEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #checkEmailVerification,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.UserModel> updateProfile({
    String? name,
    String? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #name: name,
              #profilePicture: profilePicture,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i7.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheUser(_i2.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #cacheUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserModel?> getCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUser,
          [],
        ),
        returnValue: _i5.Future<_i2.UserModel?>.value(),
      ) as _i5.Future<_i2.UserModel?>);

  @override
  _i5.Future<void> clearCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #clearCachedUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isUserCached() => (super.noSuchMethod(
        Invocation.method(
          #isUserCached,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> cacheToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getCachedToken() => (super.noSuchMethod(
        Invocation.method(
          #getCachedToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> clearCachedToken() => (super.noSuchMethod(
        Invocation.method(
          #clearCachedToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i8.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> saveAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveAuthToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [refreshToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #getAuthToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #hasRefreshToken,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> tryRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #tryRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<Map<String, dynamic>?> getTokenMetadata() => (super.noSuchMethod(
        Invocation.method(
          #getTokenMetadata,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> forceTokenRefresh() => (super.noSuchMethod(
        Invocation.method(
          #forceTokenRefresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> willTokenExpireSoon() => (super.noSuchMethod(
        Invocation.method(
          #willTokenExpireSoon,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Duration?> getTimeUntilTokenExpiry() => (super.noSuchMethod(
        Invocation.method(
          #getTimeUntilTokenExpiry,
          [],
        ),
        returnValue: _i5.Future<Duration?>.value(),
      ) as _i5.Future<Duration?>);
}

/// A class which mocks [SocialAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialAuthService extends _i1.Mock implements _i9.SocialAuthService {
  MockSocialAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<({String? displayName, String idToken})> google() =>
      (super.noSuchMethod(
        Invocation.method(
          #google,
          [],
        ),
        returnValue: _i5.Future<({String? displayName, String idToken})>.value((
          displayName: null,
          idToken: _i6.dummyValue<String>(
            this,
            Invocation.method(
              #google,
              [],
            ),
          )
        )),
      ) as _i5.Future<({String? displayName, String idToken})>);

  @override
  _i5.Future<({String? displayName, String idToken, String rawNonce})>
      apple() => (super.noSuchMethod(
            Invocation.method(
              #apple,
              [],
            ),
            returnValue: _i5.Future<
                ({
                  String? displayName,
                  String idToken,
                  String rawNonce
                })>.value((
              displayName: null,
              idToken: _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #apple,
                  [],
                ),
              ),
              rawNonce: _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #apple,
                  [],
                ),
              )
            )),
          ) as _i5.Future<
              ({String? displayName, String idToken, String rawNonce})>);
}

/// A class which mocks [PushNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationService extends _i1.Mock
    implements _i10.PushNotificationService {
  MockPushNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i11.RemoteMessage> get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _i5.Stream<_i11.RemoteMessage>.empty(),
      ) as _i5.Stream<_i11.RemoteMessage>);

  @override
  _i5.Stream<_i11.RemoteMessage> get notificationTaps => (super.noSuchMethod(
        Invocation.getter(#notificationTaps),
        returnValue: _i5.Stream<_i11.RemoteMessage>.empty(),
      ) as _i5.Stream<_i11.RemoteMessage>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCurrentToken() => (super.noSuchMethod(
        Invocation.method(
          #removeCurrentToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
