// Mocks generated by Mockito 5.4.4 from annotations
// in tulink_flutter/test/features/journeys/presentation/providers/journey_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tulink_flutter/core/errors/failure.dart' as _i5;
import 'package:tulink_flutter/features/journeys/domain/entities/journey.dart'
    as _i4;
import 'package:tulink_flutter/features/journeys/domain/repositories/journey_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JourneyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJourneyRepository extends _i1.Mock implements _i2.JourneyRepository {
  MockJourneyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<({_i4.Journey? data, _i5.Failure? failure})> createJourney({
    required String? name,
    required double? latitude,
    required double? longitude,
    required String? destinationAddress,
    required int? lagThresholdMeters,
    DateTime? scheduledFor,
    bool? autoStart = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJourney,
          [],
          {
            #name: name,
            #latitude: latitude,
            #longitude: longitude,
            #destinationAddress: destinationAddress,
            #lagThresholdMeters: lagThresholdMeters,
            #scheduledFor: scheduledFor,
            #autoStart: autoStart,
          },
        ),
        returnValue:
            _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>.value(
                (data: null, failure: null)),
      ) as _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({_i4.Journey? data, _i5.Failure? failure})> getJourneyById(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJourneyById,
          [journeyId],
        ),
        returnValue:
            _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>.value(
                (data: null, failure: null)),
      ) as _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({List<_i4.Journey>? data, _i5.Failure? failure})>
      getActiveJourneys() => (super.noSuchMethod(
            Invocation.method(
              #getActiveJourneys,
              [],
            ),
            returnValue: _i3.Future<
                ({
                  List<_i4.Journey>? data,
                  _i5.Failure? failure
                })>.value((data: null, failure: null)),
          ) as _i3.Future<({List<_i4.Journey>? data, _i5.Failure? failure})>);

  @override
  _i3.Future<List<_i4.Journey>> getCachedActiveJourneys() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedActiveJourneys,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Journey>>.value(<_i4.Journey>[]),
      ) as _i3.Future<List<_i4.Journey>>);

  @override
  _i3.Future<({_i4.Journey? data, _i5.Failure? failure})> joinJourneyByCode(
          String? inviteCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinJourneyByCode,
          [inviteCode],
        ),
        returnValue:
            _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>.value(
                (data: null, failure: null)),
      ) as _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({_i4.Journey? data, _i5.Failure? failure})> startJourney(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startJourney,
          [journeyId],
        ),
        returnValue:
            _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>.value(
                (data: null, failure: null)),
      ) as _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({_i4.Journey? data, _i5.Failure? failure})> updateJourney(
    String? journeyId,
    Map<String, dynamic>? updateData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJourney,
          [
            journeyId,
            updateData,
          ],
        ),
        returnValue:
            _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>.value(
                (data: null, failure: null)),
      ) as _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({_i4.Journey? data, _i5.Failure? failure})> endJourney(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #endJourney,
          [journeyId],
        ),
        returnValue:
            _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>.value(
                (data: null, failure: null)),
      ) as _i3.Future<({_i4.Journey? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({bool? data, _i5.Failure? failure})> cancelJourney(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelJourney,
          [journeyId],
        ),
        returnValue: _i3.Future<({bool? data, _i5.Failure? failure})>.value(
            (data: null, failure: null)),
      ) as _i3.Future<({bool? data, _i5.Failure? failure})>);

  @override
  _i3.Future<({bool? data, _i5.Failure? failure})> leaveJourney(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveJourney,
          [journeyId],
        ),
        returnValue: _i3.Future<({bool? data, _i5.Failure? failure})>.value(
            (data: null, failure: null)),
      ) as _i3.Future<({bool? data, _i5.Failure? failure})>);
}
