// Mocks generated by Mockito 5.4.4 from annotations
// in tulink_flutter/test/features/convoy/presentation/providers/convoy_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tulink_flutter/core/errors/failure.dart' as _i4;
import 'package:tulink_flutter/features/convoy/domain/entities/convoy_snapshot.dart'
    as _i5;
import 'package:tulink_flutter/features/convoy/domain/entities/journey_ended_event.dart'
    as _i9;
import 'package:tulink_flutter/features/convoy/domain/entities/participant_arrived_event.dart'
    as _i10;
import 'package:tulink_flutter/features/convoy/domain/repositories/convoy_repository.dart'
    as _i8;
import 'package:tulink_flutter/features/convoy/domain/usecases/fetch_latest_snapshot.dart'
    as _i7;
import 'package:tulink_flutter/features/convoy/domain/usecases/publish_my_position.dart'
    as _i6;
import 'package:tulink_flutter/features/convoy/domain/usecases/stream_convoy_positions.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StreamConvoyPositions].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamConvoyPositions extends _i1.Mock
    implements _i2.StreamConvoyPositions {
  MockStreamConvoyPositions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})> call(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [journeyId],
        ),
        returnValue: _i3.Stream<
            ({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>.empty(),
      ) as _i3.Stream<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>);
}

/// A class which mocks [PublishMyPosition].
///
/// See the documentation for Mockito's code generation for more information.
class MockPublishMyPosition extends _i1.Mock implements _i6.PublishMyPosition {
  MockPublishMyPosition() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> call({
    required String? journeyId,
    required double? latitude,
    required double? longitude,
    required int? timestamp,
    double? accuracy,
    double? altitude,
    double? heading,
    double? speed,
    int? batteryLevel,
    bool? isMoving,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #journeyId: journeyId,
            #latitude: latitude,
            #longitude: longitude,
            #timestamp: timestamp,
            #accuracy: accuracy,
            #altitude: altitude,
            #heading: heading,
            #speed: speed,
            #batteryLevel: batteryLevel,
            #isMoving: isMoving,
          },
        ),
        returnValue: _i3.Future<({_i4.Failure? failure, bool success})>.value(
            (failure: null, success: false)),
      ) as _i3.Future<({_i4.Failure? failure, bool success})>);
}

/// A class which mocks [FetchLatestSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchLatestSnapshot extends _i1.Mock
    implements _i7.FetchLatestSnapshot {
  MockFetchLatestSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})> call(
          String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [journeyId],
        ),
        returnValue: _i3.Future<
            ({
              _i4.Failure? failure,
              _i5.ConvoySnapshot? snapshot
            })>.value((failure: null, snapshot: null)),
      ) as _i3.Future<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>);
}

/// A class which mocks [ConvoyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvoyRepository extends _i1.Mock implements _i8.ConvoyRepository {
  MockConvoyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i5.ConvoyConnectionState> get connectionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStateStream),
        returnValue: _i3.Stream<_i5.ConvoyConnectionState>.empty(),
      ) as _i3.Stream<_i5.ConvoyConnectionState>);

  @override
  _i3.Stream<_i9.JourneyEndedEvent> get journeyEndedStream =>
      (super.noSuchMethod(
        Invocation.getter(#journeyEndedStream),
        returnValue: _i3.Stream<_i9.JourneyEndedEvent>.empty(),
      ) as _i3.Stream<_i9.JourneyEndedEvent>);

  @override
  _i3.Stream<_i10.ParticipantArrivedEvent> get participantArrivedStream =>
      (super.noSuchMethod(
        Invocation.getter(#participantArrivedStream),
        returnValue: _i3.Stream<_i10.ParticipantArrivedEvent>.empty(),
      ) as _i3.Stream<_i10.ParticipantArrivedEvent>);

  @override
  _i3.Stream<String> get journeyStartedStream => (super.noSuchMethod(
        Invocation.getter(#journeyStartedStream),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Stream<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>
      streamConvoyPositions(String? journeyId) => (super.noSuchMethod(
            Invocation.method(
              #streamConvoyPositions,
              [journeyId],
            ),
            returnValue: _i3.Stream<
                ({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>.empty(),
          ) as _i3
              .Stream<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> publishMyPosition({
    required String? journeyId,
    required double? latitude,
    required double? longitude,
    required int? timestamp,
    double? accuracy,
    double? altitude,
    double? heading,
    double? speed,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishMyPosition,
          [],
          {
            #journeyId: journeyId,
            #latitude: latitude,
            #longitude: longitude,
            #timestamp: timestamp,
            #accuracy: accuracy,
            #altitude: altitude,
            #heading: heading,
            #speed: speed,
            #metadata: metadata,
          },
        ),
        returnValue: _i3.Future<({_i4.Failure? failure, bool success})>.value(
            (failure: null, success: false)),
      ) as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>
      fetchLatestSnapshot(String? journeyId) => (super.noSuchMethod(
            Invocation.method(
              #fetchLatestSnapshot,
              [journeyId],
            ),
            returnValue: _i3.Future<
                ({
                  _i4.Failure? failure,
                  _i5.ConvoySnapshot? snapshot
                })>.value((failure: null, snapshot: null)),
          ) as _i3
              .Future<({_i4.Failure? failure, _i5.ConvoySnapshot? snapshot})>);

  @override
  _i3.Future<void> stopCoordination() => (super.noSuchMethod(
        Invocation.method(
          #stopCoordination,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
