// Mocks generated by Mockito 5.4.4 from annotations
// in tulink_flutter/test/features/journeys/data/repositories/journey_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tulink_flutter/features/journeys/data/datasources/journey_remote_data_source.dart'
    as _i3;
import 'package:tulink_flutter/features/journeys/data/models/journey_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJourneyModel_0 extends _i1.SmartFake implements _i2.JourneyModel {
  _FakeJourneyModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JourneyRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJourneyRemoteDataSource extends _i1.Mock
    implements _i3.JourneyRemoteDataSource {
  MockJourneyRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.JourneyModel> createJourney({
    required String? name,
    required double? latitude,
    required double? longitude,
    required String? destinationAddress,
    required int? lagThresholdMeters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJourney,
          [],
          {
            #name: name,
            #latitude: latitude,
            #longitude: longitude,
            #destinationAddress: destinationAddress,
            #lagThresholdMeters: lagThresholdMeters,
          },
        ),
        returnValue: _i4.Future<_i2.JourneyModel>.value(_FakeJourneyModel_0(
          this,
          Invocation.method(
            #createJourney,
            [],
            {
              #name: name,
              #latitude: latitude,
              #longitude: longitude,
              #destinationAddress: destinationAddress,
              #lagThresholdMeters: lagThresholdMeters,
            },
          ),
        )),
      ) as _i4.Future<_i2.JourneyModel>);

  @override
  _i4.Future<_i2.JourneyModel> getJourneyById(String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJourneyById,
          [journeyId],
        ),
        returnValue: _i4.Future<_i2.JourneyModel>.value(_FakeJourneyModel_0(
          this,
          Invocation.method(
            #getJourneyById,
            [journeyId],
          ),
        )),
      ) as _i4.Future<_i2.JourneyModel>);

  @override
  _i4.Future<List<_i2.JourneyModel>> getActiveJourneys() => (super.noSuchMethod(
        Invocation.method(
          #getActiveJourneys,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.JourneyModel>>.value(<_i2.JourneyModel>[]),
      ) as _i4.Future<List<_i2.JourneyModel>>);

  @override
  _i4.Future<_i2.JourneyModel> joinJourneyByCode(String? inviteCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinJourneyByCode,
          [inviteCode],
        ),
        returnValue: _i4.Future<_i2.JourneyModel>.value(_FakeJourneyModel_0(
          this,
          Invocation.method(
            #joinJourneyByCode,
            [inviteCode],
          ),
        )),
      ) as _i4.Future<_i2.JourneyModel>);

  @override
  _i4.Future<_i2.JourneyModel> startJourney(String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startJourney,
          [journeyId],
        ),
        returnValue: _i4.Future<_i2.JourneyModel>.value(_FakeJourneyModel_0(
          this,
          Invocation.method(
            #startJourney,
            [journeyId],
          ),
        )),
      ) as _i4.Future<_i2.JourneyModel>);

  @override
  _i4.Future<_i2.JourneyModel> updateJourney(
    String? journeyid,
    Map<String, dynamic>? updateData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJourney,
          [
            journeyid,
            updateData,
          ],
        ),
        returnValue: _i4.Future<_i2.JourneyModel>.value(_FakeJourneyModel_0(
          this,
          Invocation.method(
            #updateJourney,
            [
              journeyid,
              updateData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.JourneyModel>);

  @override
  _i4.Future<_i2.JourneyModel> endJourney(String? journeyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #endJourney,
          [journeyId],
        ),
        returnValue: _i4.Future<_i2.JourneyModel>.value(_FakeJourneyModel_0(
          this,
          Invocation.method(
            #endJourney,
            [journeyId],
          ),
        )),
      ) as _i4.Future<_i2.JourneyModel>);

  @override
  _i4.Future<void> cancelJourney(String? journeyId) => (super.noSuchMethod(
        Invocation.method(
          #cancelJourney,
          [journeyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> leaveJourney(String? journeyId) => (super.noSuchMethod(
        Invocation.method(
          #leaveJourney,
          [journeyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
