// Mocks generated by Mockito 5.4.4 from annotations
// in tulink_flutter/test/features/auth/presentation/auth_flow_regression_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tulink_flutter/core/errors/failure.dart' as _i4;
import 'package:tulink_flutter/features/auth/domain/entities/user_entity.dart'
    as _i5;
import 'package:tulink_flutter/features/auth/domain/repositories/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signIn({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signUp({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, String? token, _i5.UserEntity? user})>
  signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
                >.value((failure: null, token: null, user: null)),
          )
          as _i3.Future<
            ({_i4.Failure? failure, String? token, _i5.UserEntity? user})
          >);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, _i5.UserEntity? user})
                >.value((failure: null, user: null)),
          )
          as _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})>);

  @override
  _i3.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<({_i4.Failure? failure, String? token})> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, String? token})>.value((
                  failure: null,
                  token: null,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, String? token})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> verifyEmail({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})> updateProfile({
    String? name,
    String? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #profilePicture: profilePicture,
            }),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, _i5.UserEntity? user})
                >.value((failure: null, user: null)),
          )
          as _i3.Future<({_i4.Failure? failure, _i5.UserEntity? user})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool success})> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue:
                _i3.Future<({_i4.Failure? failure, bool success})>.value((
                  failure: null,
                  success: false,
                )),
          )
          as _i3.Future<({_i4.Failure? failure, bool success})>);

  @override
  _i3.Future<({_i4.Failure? failure, bool isEmailVerified})>
  checkEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailVerification, []),
            returnValue:
                _i3.Future<
                  ({_i4.Failure? failure, bool isEmailVerified})
                >.value((failure: null, isEmailVerified: false)),
          )
          as _i3.Future<({_i4.Failure? failure, bool isEmailVerified})>);
}
